global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts-orbit.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "orbit-api"
    metrics_path: /v1/metrics
    static_configs:
      - targets: ["orbit-api:8000"]
